export const ADD_MEDIA_TYPE = 'ADD_MEDIA_TYPE'
export const ADD_MOVIE_ITEM = 'ADD_MOVIE_ITEM'
export const GET_MOVIE_FAIL = 'GET_MOVIE_FAIL'

export const ADD_POPULAR_MOVIE_REQUEST = 'ADD_POPULAR_MOVIE_REQUEST'
export const ADD_POPULAR_MOVIE = 'ADD_POPULAR_MOVIE'
export const ADD_POPULAR_MOVIE_FAILL = 'ADD_POPULAR_MOVIE_FAILL'
