export const ADD_MEDIA_TYPE = 'ADD_MEDIA_TYPE'

export const ADD_MOVIE_ITEM = 'ADD_MOVIE_ITEM'
export const GET_MOVIE_FAIL = 'GET_MOVIE_FAIL'

export const ADD_POPULAR_MOVIE_REQUEST = 'ADD_POPULAR_MOVIE_REQUEST'
export const ADD_POPULAR_MOVIE = 'ADD_POPULAR_MOVIE'
export const ADD_POPULAR_MOVIE_FAILL = 'ADD_POPULAR_MOVIE_FAILL'

export const FEATURED_MOVIE_REQUEST = 'FEATURED_MOVIE_REQUEST'
export const FEATURED_MOVIE = 'FEATURED_MOVIE'
export const FEATURED_MOVIE_FAIL = 'FEATURED_MOVIE_FAIL'

export const GENRES_MOVIE_REQUEST = 'GENRES_MOVIE_REQUEST'
export const GENRES_MOVIE = 'GENRES_MOVIE'
export const GENRES_MOVIE_FAIL = 'GENRES_MOVIE_FAIL'

export const GET_MOVIE_REQUEST = "GET_MOVIE_REQUEST";
export const GET_MOVIE = "GET_MOVIE";

export const GET_LIST_REQUEST = "GET_LIST_REQUEST";
export const GET_LIST = "GET_LIST";
export const GET_LIST_FAIL = "GET_LIST_FAIL";