export const GET_TORRENTS_REQUEST = "GET_TORRENTS_REQUEST";
export const GET_TORRENTS = "GET_TORRENTS";
export const PLAY_TORRENT = "PLAY_TORRENT";
export const STOP_TORRENT = "STOP_TORRENT";
export const RESET_STATES_TORRENTS = "RESET_STATES_TORRENTS";